### ISSUE TITLE
Unpin Travis CI from Node 10.4.1

### ISSUE THREAD

**Issue by mintyfloss** [RetailMeNotSandbox/roux-handlebars-tools#29]
We're currently pinning to Node 10.4.1 in TravisCI because of unit test errors when using Node 10.5. There's a issue in mock-fs that is tracking this issue https://github.com/tschaub/mock-fs/issues/238.

**Comment by pierceray** [comment]
I believe we need to switch using an actual directory structure for the unit testing according to what @jared-stilwell conveyed in person.

**Comment by pierceray** [comment]
There was a release fo mockfs that fixes this issue.  We should just bump the dependency to 4.8.0 as the min required version.

https://github.com/tschaub/mock-fs/releases/tag/v4.8.0

**Comment by pierceray** [comment]
Fixed in 5a2a672ecbee445e13ec7e2b26d236d3f396bfaa
